"$schema" = 'https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json'
console_title_template = '{{.PWD}}_%_{{.Shell}}'
version = 2

[palette]
os = '#ACB0BE'
pink = '#F5BDE6'
lavender = '#B7BDF8'
blue = '#8AADF4'
wight = '#FFFFFF'
text = '#494D64'
dark_bk = '#18161a'
yellow_f = '#ab9127'
red = '#ef5350'
path_f = '#16012e'
light_bk = '#65656e'
black = '#0'
light_green = '#0ecc0e'
dark_green = '#069c31'
light_red = '#ef5350'



[[blocks]]
alignment = 'left'
type = 'prompt'

[[blocks.segments]]
background = 'p:dark_bk'
foreground = 'p:yellow_f'
style = 'powerline'
template = '{{.Icon}} '
type = 'os'
[[blocks.segments]]
background = 'p:dark_bk'
foreground = 'p:yellow_f'
style = 'powerline'
template = "\uf489 {{ .Name }}"
type = 'shell'
[[blocks.segments]]
background = 'p:dark_bk'
foreground = 'p:yellow_f'
style = 'powerline'
template = " {{ if .SSHSession }}\ueb39 {{ end }}{{ if .WSL }}\ueb7a {{ end }}{{if .Root}}\uf0e7{{ else }}\uf2bd{{ end }} {{ .UserName }}@{{ .HostName }}"
foreground_templates = ['{{ if .Root }}p:red{{ end }}']
type = 'session'
[blocks.segments.properties]
display_host = true


[[blocks.segments]]
foreground = 'p:yellow_f'
background = 'p:dark_bk'
style = 'powerline'
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
type = 'git'

[blocks.segments.properties]
branch_icon = "\ue725 "
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true
fetch_worktree_count = true


[[blocks]]
alignment = 'right'
type = 'prompt'

[[blocks.segments]]
foreground = '#a9ffb4'
style = 'plain'
type = 'text'

[[blocks.segments]]
foreground = 'p:light_green'
foreground_templates = ['{{ if ne .Code 0 }}p:light_red{{ end }}']
style = 'diamond'
template = "{{ if eq .Code 0 }}<p:light_green>\uebb1</>{{ else }}<p:light_red>\uf467</>{{ end }} {{ .FormattedMs }}"
type = 'executiontime'

[blocks.segments.properties]
style = 'austin'
threshold = 1

[[blocks.segments]]
type = "java"
style = "powerline"
foreground = "p:blue"
background = "transparent"
template = " \ue256 {{ if .Error }}{{ .Error }}{{ else }}{{ .Major }}{{ end }}"

[[blocks.segments]]
type = "python"
style = "powerline"
foreground = "p:lavender"
background = "transparent"
template = " \ue256 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"
[blocks.segments.properties]
display_mode = "context"


[[blocks.segments]]
foreground = '#4b3bb8'
style = 'diamond'
template = " <p:dark_green>\ue266 </>{{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}"
type = 'sysinfo'

[[blocks.segments]]
type = "battery"
template = " {{ if not .Error }}{{ .State.String }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295"
style = 'diamond'
background = "#f36943"
background_templates = [
    "{{if eq \"Charging\" .State.String}}#b8e994{{end}}",
    "{{if eq \"Discharging\" .State.String}}#fff34e{{end}}",
    "{{if eq \"Full\" .State.String}}#33DD2D{{end}}"
]
foreground = "#262626"
[blocks.segments.properties]
charged_icon = " \uf240 "
charging_icon = " \uf1e6 "
discharging_icon = " \ue234 "


[[blocks]]
alignment = 'left'
type = 'prompt'
newline = true

[[blocks.segments]]
foreground = 'p:path_f'
background = 'p:light_bk'
style = 'diamond'
leading_diamond = "<#211700>\ue285 </>"
trailing_diamond  = ""
template = "\ue5ff {{ .Path }}"
type = 'path'

[blocks.segments.properties]
max_depth = 8
folder_icon = "\uf07b"
folder_separator_icon = '/'
home_icon = "<p:path_f>\ueb06 </>"
style = 'agnoster_short'


[[blocks.segments]]
foreground = '#011a01'
background = 'p:light_bk'
style = 'plain'
template = " {{ if .Root }}\uf292{{ else }}𝝀{{ end }}_"
type = 'status'
foreground_templates = ['{{ if gt .Code 0 }}#75020c{{ end }}']

[blocks.segments.properties]
always_enabled = true

[transient_prompt]
# background = 'transparent'
background = '#4d4d4f'
template = "{{ if .Root }}<#ef5350>\uf292_</>{{ else }}<#211700>𝝀_</>{{ end }}"
